services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
